# --- Power / sleep ---
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=60000

# --- Split BLE (делает правую отзывчивее после простоя) ---
CONFIG_ZMK_SPLIT_BLE_PREF_INT=6
CONFIG_ZMK_SPLIT_BLE_PREF_LATENCY=0
CONFIG_ZMK_SPLIT_BLE_PREF_TIMEOUT=400

# --- OLED display ---
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Драйвер дисплея (первым пробуем SSD1306)
CONFIG_SSD1306=y
