# --- Power / sleep ---
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_TIMEOUT=60000

# --- OLED display ---
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

CONFIG_SSD1306=y
CONFIG_SSD1306_SH1106=n
